baseurl = "https://www.insci.io" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Insci Analytics - Democratizing AI!"
theme = "hugo-universal-theme"
themesDir = "current_theme/"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

# [[menu.main]]
#     name       = "Option 1: Default Page"
#     url        = "/"
#     weight     = 1
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 2: Application"
#     url        = "/"
#     weight     = 2
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 3: Startup"
#     url        = "/"
#     weight     = 3
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 4: Agency"
#     url        = "/"
#     weight     = 4
#     parent     = "menu.home"

# [[menu.main]]
#     name       = "Option 5: Portfolio"
#     url        = "/"
#     weight     = 5
#     parent     = "menu.home"

[[menu.main]]
    name       = "Specializations"
    identifier = "menu.specializations"
    url        = "/img/template-easy-customize.png"
    weight     = 3

[[menu.main]]
    name       = "Chatbot + NLP"
    identifier = "section.chatbot"
    url        = ""
    weight     = 1
    parent     = "menu.specializations"
    

[[menu.main]]
    name       = "Header variations"
    identifier = "section.headervariations"
    url        = ""
    weight     = 2
    parent     = "menu.specializations"
    post       = 2

[[menu.main]]
    name       = "Accordions"
    url        = ""
    weight     = 1
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Alerts"
    url        = ""
    weight     = 2
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Buttons"
    url        = ""
    weight     = 3
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Content Boxes"
    url        = ""
    weight     = 4
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Horizontal Blocks"
    url        = ""
    weight     = 5
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Pagination"
    url        = ""
    weight     = 6
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Tabs"
    url        = ""
    weight     = 7
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Typography"
    url        = ""
    weight     = 8
    parent     = "menu.specializations"

[[menu.main]]
    name       = "Default Sticky Header"
    url        = ""
    weight     = 1
    parent     = "section.headervariations"

[[menu.main]]
    name       = "No Sticky Header"
    url        = ""
    weight     = 2
    parent     = "section.headervariations"

[[menu.main]]
    name       = "Light Header"
    url        = ""
    weight     = 3
    parent     = "section.headervariations"

[[menu.main]]
    name       = "Products"
    identifier = "menu.products"
    url        = "/products/"
    weight     = 3



[[menu.main]]
    name       = "About"
    identifier = "section.about"
    url        = ""
    weight     = 4

[[menu.main]]
    name       = "About Us"
    identifier = "menu.about_us"
    url        = "/about_us/"
    weight     = 1
    parent     = "section.about"


[[menu.main]]
    name       = "Our Team"
    identifier = "team"
    url        = "/team/"
    weight     = 2
    parent     = "section.about"



# [[menu.main]]
#     name       = "Marketing"
#     identifier = "section.marketing"
#     url        = ""
#     weight     = 3
#     parent     = "menu.portfolio"
#     post       = 2

# [[menu.main]]
#     name       = "Packages"
#     url        = ""
#     weight     = 1
#     parent     = "section.marketing"

# [[menu.main]]
#     name       = "All Pages"
#     identifier = "menu.allpages"
#     url        = ""
#     weight     = 4

# [[menu.main]]
#     name       = "Home"
#     identifier = "section.ap-home"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "About"
#     identifier = "section.ap-about"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Marketing"
#     identifier = "section.ap-marketing"
#     url        = ""
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Portfolio"
#     identifier = "section.ap-portfolio"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "User Pages"
#     identifier = "section.ap-userpages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "Shop"
#     identifier = "section.ap-shop"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Shop - Order Process"
#     identifier = "section.ap-shoporderprocess"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Contact"
#     identifier = "section.ap-contact"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Pages"
#     identifier = "section.ap-pages"
#     url        = ""
#     weight     = 2
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Blog"
#     identifier = "section.ap-blog"
#     url        = "/blog/"
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Blog Listing Big"
#     url        = "/blog/"
#     weight     = 1
#     parent     = "section.ap-blog"

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7

# [[menu.main]]
#     identifier = "team"
#     name       = "About Us"
#     url        = "/team/"
#     weight     = 8
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:contact@insci.io"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Insci Analytics"
    defaultKeywords = ["AI", "Insci", "Analytics"]
    mainSections = ["blog"]
    prodsec = ["products"]
    defaultDescription = "Made @Insci with magic!"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>We are a AI-first company, <br> made by <strong><em>scientists, engineers and growth-hackers!</em></strong></p>"
    copyright = "Copyright (c) 2022, Insci Analytics Pvt. Ltd. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 1, 2022"

    disabled_logo = true
    logo_text = "INSCI ANALYTICS"

    logo = "img/insci.png"
    logo_small = "img/insci.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Insci Analytics</strong>
        <br>15th Cross Rd, ITI Layout,
        <br> J. P. Nagar, Bengaluru
        <br>Karnataka 560078
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    enable=true
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.specializations]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All specializations are defined in their own files. You can find example items
    # at 'exampleSite/data/specializations'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "What Our Clients Say!"
    subtitle = ""

[params.showcase]
    enable = true
    # All team are defined in their own files. You can find example items
    # at 'exampleSite/data/team'.
    # For more informtion take a look at the README.


[params.team]
    enable = true
    # All team are defined in their own files. You can find example items
    # at 'exampleSite/data/team'.
    # For more informtion take a look at the README.
    title = "Who are we?"
    subtitle = ""

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""


[params.products]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Products"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Contact Us"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "/contact"
    link_text = "contact us"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
